name: music
description: "A new Flutter project."
publish_to: "none"
version: 1.0.5
environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## 通用
  # 网络请求
  dio: ^5.7.0
  # 路由,状态管理
  get: ^4.6.6
  # 存储
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # 屏幕适配
  flutter_screenutil: ^5.9.3
  # 日志
  logger: ^2.5.0

  ## 音频相关
  # 音频播放
  audioplayers: ^6.1.0
  # 系统音频操作代理
  audio_service: ^0.18.16
  # 读取音频元数据
  id3tag: ^0.2.0

  ## 工具
  # s3
  minio: ^3.5.7
  # 组件显示监听
  visibility_detector: ^0.4.0+2
  # 键盘焦点取消
  keyboard_dismisser: ^3.0.0
  # 包信息
  package_info_plus: ^8.1.2
  window_manager: ^0.4.3
  # 路径提供
  path_provider: ^2.1.5
  # 列表优化
  keframe: ^3.0.0
  # 后台常驻
  flutter_background: ^1.3.0+1

  ## UI
  # 模糊
  blur: ^4.0.0
  # 进度条
  audio_video_progress_bar: ^2.0.3
  # 弹窗提醒
  flutter_easyloading: ^3.0.5
  # 跳转列表索引
  indexed_list_view: ^4.0.0
  # 小音频波浪
  mini_music_visualizer: ^1.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  # flutter packages pub run build_runner build
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
